name: Run Script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        run: python gl-gh-automation.py
        working-directory: ./git_clone-automation  # Adjust the path as per your directory structure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
